<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slider extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'image',
        'order',
        'visible',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    public static function images() {
        return self::pluck('image', 'id');
    }

    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
